# Example secrets for development.
# Replace the placeholder values below with your real keys/connection strings.
# Streamlit requires a valid TOML file here; an empty file can cause a FileNotFoundError
# when `st.secrets` tries to parse secrets.

[openai]
# DeepSeek / OpenAI-like API key used by the app (ds_api_key is read in the code)
ds_api_key = "sk-dc9d1a5bfedd4075803e48248eec6071"

[supabase]
# SQLAlchemy connection string for Supabase (used by create_engine)
# Example: "postgresql://username:password@host:5432/database"
conn = "postgresql://postgres:Bai!545579@db.hsgxjdohxbwxmnkzapxl.supabase.co:5432/postgres"
